# Generated by Django 5.0 on 2024-03-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_stories', '0002_alter_review_options_alter_type_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='filtered',
            field=models.CharField(blank=True, choices=[('Yes', 'Filtered'), ('No', 'Unfiltered')], help_text='Choose filtered or unfiltered beer!', max_length=20, null=True),
        ),
    ]
