# Generated by Django 5.0 on 2024-03-28 15:53

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_stories', '0003_alter_review_filtered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=10000, verbose_name='description'),
        ),
    ]
