# Generated by Django 5.0 on 2024-03-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_stories', '0005_alter_review_filtered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='color',
            field=models.CharField(choices=[(' Light / Straw ', ' Light / Straw '), (' Amber', 'Amber '), (' Copper / Reddish-Brown ', ' Copper / Reddish-Brown '), (' Brown ', ' Brown '), (' Black ', ' Black ')], help_text='Choose your colour of beer!', max_length=30),
        ),
    ]
